### ISSUE TITLE
using add() with Box2d objects

### ISSUE THREAD

**Issue by jamessimo** [iioinc/iio.js#24]
Hey guys,  I want to draw a coloured iio rect with a small image in the center, however
 ```` .setFillStyle() ```` will always draw over the image ```` .addImage() ````
 is there a way around this? (if you set the alpha to 50% I can see the image in the center) 

Cheers!

**Comment by jamessimo** [comment]
Is this still an open issue in version 1.4?

**Comment by sbiermanlytle** [comment]
I think it is, the Box2d integration is basically the same in 1.4 as in 1.2. Still on the priority list though.

**Comment by sbiermanlytle** [comment]
The new docs discuss this aspect of using iio object management vs Box2d object management: http://iio.js.org/#api/extras/box2d. Deeper mobile integration is more of a priority than deeper Box2d integration, so it may be a while until you can use iio's management functions on B2d objects
