### ISSUE TITLE
iio 1.3 box2D version? 

### ISSUE THREAD

**Issue by jamessimo** [iioinc/iio.js#25]
Hey I was just wondering what version of box2D the new version will use, the one hosted on google I find to be out of date (JUN 2011 https://code.google.com/p/box2dweb/downloads/list ) and there is only one contributor.
For some users this bug may be a deal breaker https://code.google.com/p/box2dweb/issues/detail?id=29 . (this bug can be patched) 

If I am not working with iio I tent to opt for this version of box2D https://github.com/kripken/box2d.js/

**Comment by sbiermanlytle** [comment]
So v1.4 ended up sticking with Box2dWeb (https://github.com/hecht-software/box2dweb). I tried using the kripken version but I couldn't figure out a way to interface its shapes with iio's rendering engine.

It looks like there have been new updates to the demos though that I didn't see when I started looking into it: http://kripken.github.io/box2d.js/webgl_demo/box2d.html

I will try again at some point, I think this version is a better choice
