### ISSUE TITLE
How to use  HTML  such  as  <input >  with  iio ?

### ISSUE THREAD

**Issue by FranklinZhang91** [iioinc/iio.js#41]
First, iio is a great engine for drawing in Web. I am student in China, and sorry for my poor English. My question is that I want use some  HTML in iio because I want to use Chinese (iio.Text do not support Chinese), but it is banned. So how can I do~~~~~

**Comment by jamessimo** [comment]
What font are you loading in to use? Also make sure your files are being saved as UTF-8 as this can cause issues.

**Comment by sbiermanlytle** [comment]
you can access any HTML DOM element with standard JavaScript: `document. getElementById()` or with jQuery. Once you have a reference to the DOM element, you can access its text value

**Comment by sbiermanlytle** [comment]
reopen if you are still having trouble

**Comment by FranklinZhang91** [comment]
I have solved it, thank you so much.
